<script>
  import * as Icon from '$lib';
  let size = '50';
</script>

<Icon.A1Password {size} />
<Icon.Acast {size} />
<Icon.Access {size} />
<Icon.Activitypub {size} />
<Icon.Adobe {size} />
<Icon.Airbnb {size} />
<Icon.Amazon {size} />
<Icon.Amazon_alexa {size} />
<Icon.Amazon_s3 {size} />
<Icon.Amberframework {size} />
<Icon.Andotp {size} />
<Icon.Android {size} />
<Icon.Angellist {size} />
<Icon.Angular {size} />
<Icon.Ansible {size} />
<Icon.Apereo {size} />
<Icon.Apple {size} />
<Icon.Apple_music {size} />
<Icon.Arch_linux {size} />
<Icon.Atom {size} />
<Icon.Auth0 {size} />
<Icon.Authy {size} />
<Icon.Backbone {size} />
<Icon.Badoo {size} />
<Icon.Baidu {size} />
<Icon.Bandcamp {size} />
<Icon.Behance {size} />
<Icon.Bing {size} />
<Icon.Bitbucket {size} />
<Icon.Bitcoin {size} />
<Icon.Bitwarden {size} />
<Icon.Blender {size} />
<Icon.Blogger {size} />
<Icon.Bluetooth {size} />
<Icon.Brave {size} />
<Icon.Briar {size} />
<Icon.Buffer {size} />
<Icon.Bugcrowd {size} />
<Icon.Bun {size} />
<Icon.Calendar {size} />
<Icon.Centos {size} />
<Icon.Chrome {size} />
<Icon.Chromium {size} />
<Icon.Citrix {size} />
<Icon.Citrix_compact {size} />
<Icon.Clojure {size} />
<Icon.Cloudflare {size} />
<Icon.Codeberg {size} />
<Icon.Codepen {size} />
<Icon.Coffeescript {size} />
<Icon.Coil {size} />
<Icon.Coinpot {size} />
<Icon.Colaboratory {size} />
<Icon.Cplusplus {size} />
<Icon.Crystal {size} />
<Icon.Css3 {size} />
<Icon.Dart {size} />
<Icon.Datacamp {size} />
<Icon.Debian {size} />
<Icon.Deezer {size} />
<Icon.Delicious {size} />
<Icon.Dev_to {size} />
<Icon.Deviantart {size} />
<Icon.Digidentity {size} />
<Icon.Digitalocean {size} />
<Icon.Discord {size} />
<Icon.Disqus {size} />
<Icon.Djangoproject {size} />
<Icon.Docker {size} />
<Icon.Dribbble {size} />
<Icon.Drone {size} />
<Icon.Dropbox {size} />
<Icon.Drupal {size} />
<Icon.Duckduckgo {size} />
<Icon.Ea {size} />
<Icon.Ebay {size} />
<Icon.Edge {size} />
<Icon.Elastic {size} />
<Icon.Element {size} />
<Icon.Elementaryos {size} />
<Icon.Email {size} />
<Icon.Endeavouros {size} />
<Icon.Epub {size} />
<Icon.Espressif {size} />
<Icon.Ethereum {size} />
<Icon.Etsy {size} />
<Icon.Evernote {size} />
<Icon.Expressionengine {size} />
<Icon.Facebook {size} />
<Icon.Filestash {size} />
<Icon.Finder {size} />
<Icon.Firefox {size} />
<Icon.Flattr {size} />
<Icon.Flickr {size} />
<Icon.Floatplane {size} />
<Icon.Flutter {size} />
<Icon.Foobar2000 {size} />
<Icon.Freebsd {size} />
<Icon.Freecodecamp {size} />
<Icon.Friendica {size} />
<Icon.Fritz {size} />
<Icon.Gandi {size} />
<Icon.Gatehub {size} />
<Icon.Ghost {size} />
<Icon.Git {size} />
<Icon.Gitea {size} />
<Icon.Github {size} />
<Icon.Gitlab {size} />
<Icon.Gitpod {size} />
<Icon.Glitch {size} />
<Icon.Gmail {size} />
<Icon.Gmail_old {size} />
<Icon.Go {size} />
<Icon.Godot {size} />
<Icon.Gogcom {size} />
<Icon.Gojek {size} />
<Icon.Goodreads {size} />
<Icon.Google {size} />
<Icon.Google_assistant {size} />
<Icon.Google_calendar {size} />
<Icon.Google_collaborative_content_tools {size} />
<Icon.Google_docs_editors {size} />
<Icon.Google_drive {size} />
<Icon.Google_drive_old {size} />
<Icon.Google_maps {size} />
<Icon.Google_maps_old {size} />
<Icon.Google_meet {size} />
<Icon.Google_play {size} />
<Icon.Google_plus {size} />
<Icon.Google_podcasts {size} />
<Icon.Google_scholar {size} />
<Icon.Gradle {size} />
<Icon.Grafana {size} />
<Icon.Guacamole {size} />
<Icon.Guilded {size} />
<Icon.Hackernews {size} />
<Icon.Hackerone {size} />
<Icon.Haml {size} />
<Icon.Heroku {size} />
<Icon.Homekit {size} />
<Icon.Hp {size} />
<Icon.Html5 {size} />
<Icon.Hulu {size} />
<Icon.Humblebundle {size} />
<Icon.I18next {size} />
<Icon.Ibm {size} />
<Icon.Iheartradio {size} />
<Icon.Imdb {size} />
<Icon.Imgur {size} />
<Icon.Instagram {size} />
<Icon.Intel {size} />
<Icon.Intercom {size} />
<Icon.Internet_archive {size} />
<Icon.Itch_io {size} />
<Icon.Itunes_podcasts {size} />
<Icon.Jacobin {size} />
<Icon.Java {size} />
<Icon.Javascript {size} />
<Icon.Jellyfin {size} />
<Icon.Json {size} />
<Icon.JsonLd {size} />
<Icon.Jsonfeed {size} />
<Icon.Julia {size} />
<Icon.Kaggle {size} />
<Icon.Keepassdx {size} />
<Icon.Kemal {size} />
<Icon.Keskonfai {size} />
<Icon.Keybase {size} />
<Icon.Kickstarter {size} />
<Icon.KoFi {size} />
<Icon.Kodi {size} />
<Icon.Kotlin {size} />
<Icon.Laravel {size} />
<Icon.Lastpass {size} />
<Icon.Liberapay {size} />
<Icon.Line {size} />
<Icon.Linearapp {size} />
<Icon.Linkedin {size} />
<Icon.Linux {size} />
<Icon.Linux_mint {size} />
<Icon.Lobsters {size} />
<Icon.Lock {size} />
<Icon.Logitech {size} />
<Icon.Luckyframework {size} />
<Icon.Macos {size} />
<Icon.Mail {size} />
<Icon.Mailchimp {size} />
<Icon.Malt {size} />
<Icon.Manjaro {size} />
<Icon.Markdown {size} />
<Icon.Mastodon {size} />
<Icon.Matrix {size} />
<Icon.Mattermost {size} />
<Icon.Medium {size} />
<Icon.Meetup {size} />
<Icon.Messenger {size} />
<Icon.Microformats {size} />
<Icon.Microsoft {size} />
<Icon.Minecraft {size} />
<Icon.Netbeans {size} />
<Icon.Netflix {size} />
<Icon.Nextcloud {size} />
<Icon.Nginx {size} />
<Icon.Nhs {size} />
<Icon.Nixos {size} />
<Icon.Npm {size} />
<Icon.Ok {size} />
<Icon.Olympics {size} />
<Icon.Openbenches {size} />
<Icon.Openbugbounty {size} />
<Icon.Opencast {size} />
<Icon.Opencollective {size} />
<Icon.Opencores {size} />
<Icon.Opensource {size} />
<Icon.Openstreetmap {size} />
<Icon.Openvpn {size} />
<Icon.Opera {size} />
<Icon.Orcid {size} />
<Icon.Origin {size} />
<Icon.Outlook {size} />
<Icon.Overcast {size} />
<Icon.Overleaf {size} />
<Icon.Patreon {size} />
<Icon.Paypal {size} />
<Icon.Pdf {size} />
<Icon.Phone {size} />
<Icon.Php {size} />
<Icon.Pinboard {size} />
<Icon.Pinterest {size} />
<Icon.Pixelfed {size} />
<Icon.Plex {size} />
<Icon.Pocket {size} />
<Icon.Pocketcasts {size} />
<Icon.Popos {size} />
<Icon.Pornhub {size} />
<Icon.Powershell {size} />
<Icon.Preact {size} />
<Icon.Print {size} />
<Icon.Protonmail {size} />
<Icon.Python {size} />
<Icon.Qq {size} />
<Icon.Quora {size} />
<Icon.Raspberry_pi {size} />
<Icon.React {size} />
<Icon.Reddit {size} />
<Icon.Redhat {size} />
<Icon.Researchgate {size} />
<Icon.Roundcube {size} />
<Icon.Rss {size} />
<Icon.Ruby {size} />
<Icon.Rubygems {size} />
<Icon.Rubyonrails {size} />
<Icon.Rust {size} />
<Icon.Safari {size} />
<Icon.Samsung {size} />
<Icon.Samsung_internet {size} />
<Icon.Samsung_s {size} />
<Icon.Samsung_swoop {size} />
<Icon.Sass {size} />
<Icon.Semaphoreci {size} />
<Icon.Sentry {size} />
<Icon.Signal {size} />
<Icon.Sketch {size} />
<Icon.Skype {size} />
<Icon.Slack {size} />
<Icon.Slideshare {size} />
<Icon.Snapchat {size} />
<Icon.Sogo {size} />
<Icon.Solidity {size} />
<Icon.Soundcloud {size} />
<Icon.Spotify {size} />
<Icon.Square_cash {size} />
<Icon.Stackexchange {size} />
<Icon.Stackoverflow {size} />
<Icon.Steam {size} />
<Icon.Stitcher {size} />
<Icon.Strava {size} />
<Icon.Stumbleupon {size} />
<Icon.Sublimemerge {size} />
<Icon.Sublimetext {size} />
<Icon.Subscribestar {size} />
<Icon.Svelte {size} />
<Icon.Svg {size} />
<Icon.Symantec {size} />
<Icon.Taiga {size} />
<Icon.Teamspeak {size} />
<Icon.Telegram {size} />
<Icon.Terraform {size} />
<Icon.Thisamericanlife {size} />
<Icon.Threema {size} />
<Icon.Tiktok {size} />
<Icon.Todoist {size} />
<Icon.Tox {size} />
<Icon.Trello {size} />
<Icon.Tripadvisor {size} />
<Icon.Tumblr {size} />
<Icon.Tunein {size} />
<Icon.Tutanota {size} />
<Icon.Twilio {size} />
<Icon.Twitch {size} />
<Icon.Twitter {size} />
<Icon.Typescript {size} />
<Icon.Uber {size} />
<Icon.Ubiquiti {size} />
<Icon.Ubisoft {size} />
<Icon.Ubuntu {size} />
<Icon.Udemy {size} />
<Icon.Unicode {size} />
<Icon.Untappd {size} />
<Icon.Uphold {size} />
<Icon.Uplay {size} />
<Icon.Upwork {size} />
<Icon.Vagrant {size} />
<Icon.Vegetarian {size} />
<Icon.Venmo {size} />
<Icon.Viber {size} />
<Icon.Vim {size} />
<Icon.Vimeo {size} />
<Icon.Visualstudiocode {size} />
<Icon.Vivino {size} />
<Icon.Vk {size} />
<Icon.Vlc {size} />
<Icon.Vue {size} />
<Icon.W3c {size} />
<Icon.Webassembly {size} />
<Icon.Webmention {size} />
<Icon.Wechat {size} />
<Icon.Wekan {size} />
<Icon.Whatsapp {size} />
<Icon.Whatwg {size} />
<Icon.Wifi {size} />
<Icon.Wikipedia {size} />
<Icon.Windows {size} />
<Icon.Wire {size} />
<Icon.Wireguard {size} />
<Icon.Wordpress {size} />
<Icon.Workato {size} />
<Icon.Xing {size} />
<Icon.Xmpp {size} />
<Icon.Yahoo {size} />
<Icon.Yammer {size} />
<Icon.Yarn {size} />
<Icon.Yelp {size} />
<Icon.Youtube {size} />
<Icon.Yubico {size} />
<Icon.Zoom {size} />
<Icon.Zorinos {size} />
